version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Docker/Nginx/Dockerfile
    networks:
      - gym-workouts-network
    ports:
      - "80:80"

  mailer-service:
    container_name: mailer-service
    build:
      context: .
      dockerfile: ./Docker/MailerService/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - gym-workouts-network

  gym-app:
    container_name: gym-app
    build:
      context: .
      dockerfile: ./Docker/GymApp/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - gym-workouts-network
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  database:
    container_name: database
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: main
    ports:
      - "3307:3306"
    networks:
      - gym-workouts-network
    volumes:
      - database-volume:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - gym-workouts-network

networks:
  gym-workouts-network:
    driver: bridge

volumes:
  database-volume: