version: "3"
services:
  spring-boot-app:
    container_name: gym-workouts
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - gym-workouts-network
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  database:
    container_name: database
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: gymworokoutslibrary
    ports:
      - "3307:3306"
    networks:
      - gym-workouts-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - gym-workouts-network

networks:
  gym-workouts-network:
    driver: bridge
